// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package factory

import (
	"github.com/google/wire"
	"wire_practice_demo/conf"
	"wire_practice_demo/repository"
	"wire_practice_demo/service"
)

// Injectors from wire.go:

func NewBookShopService() *service.BookShop {
	bookRep := repository.NewBookRep()
	userRep := repository.NewUserRep()
	bookShop := service.NewBookShopService(bookRep, userRep)
	return bookShop
}

// wire.go:

var SuperSet = wire.NewSet(conf.NewDbConf, repository.NewBookRep, repository.NewUserRep, repository.NewUserRepPtr, service.NewBookShopService)
